# config.yaml
appId: com.wdiodemoapp
# testOutputDir: wdio/reports/
flows:

  - "**"
  - login/failure/*
  - login/success/*
  - register/failure/*
  - register/success/*
  - swipe/*


 

  # Platform Configuration
platform:
  android:
    disableAnimations: true
