# config.yaml
appId: com.wdiodemoapp
# testOutputDir: wdio/reports/
flows:

  - "./maestro/tests/E2E/login/auth/failure/*.yaml"
  - "./maestro/tests/E2E/login/auth/success/*.yaml"
  
  - "./maestro/tests/E2E/register/failure/*.yaml"
  - "./maestro/tests/E2E/register/success/*.yaml"

  - "./maestro/tests/E2E/Swipe/*.yaml"

  # Platform Configuration
platform:
  android:
    disableAnimations: true
