name: Build and run Maestro tests (Native Android)

on:
  push:
    branches: [ main ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    outputs:
      app: app/build/outputs/apk/debug
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
  
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          # note that you can supply the project id any way you like, it is not secret
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: android.wdio.native.app.v1.0.8.apk


      - name: Parse maestro tests and send results to slack
        id: test-results
        uses: brett-james-rocketlab/maestro-test-results-to-slack@main
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

          

      # ENVIAR NOTIFICAÇÃO PARA O SLACK

      - name: Send Slack Notification
        if: always() # Garantir que a notificação seja enviada mesmo se o passo anterior falhar
        run: |
          STATUS="${{ steps.maestro.outcome }}"
          if [ "$STATUS" == "success" ]; then
            MESSAGE="✅ Testes finalizados com sucesso no Maestro Cloud!"
          else
            MESSAGE="❌ Falha ao executar testes no Maestro Cloud!"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\": \"$MESSAGE\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
