name: Build and run Maestro tests (Native Android)

on:
  push:
    branches: [ main ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      # - name: Build APK
      #   run: ./gradlew assembleDebug

      - name: Run Maestro Cloud Tests
        id: maestro
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: android.wdio.native.app.v1.0.8.apk

          

      # ENVIAR NOTIFICAÇÃO PARA O SLACK

      - name: Send Slack Notification
        if: always() # Garantir que a notificação seja enviada mesmo se o passo anterior falhar
        run: |
          STATUS="${{ steps.maestro.outcome }}"
          if [ "$STATUS" == "success" ]; then
            MESSAGE="✅ Testes finalizados com sucesso no Maestro Cloud!"
          else
            MESSAGE="❌ Falha ao executar testes no Maestro Cloud!"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\": \"$MESSAGE\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
