name: Build and run Maestro tests (Native Android)

on:
  push:
    branches: [ main ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Run Maestro Cloud
        id: maestro
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: android.wdio.native.app.v1.0.8.apk
          workspace: '.maestro/'


      - name: Slack Notification - Success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL}}
          SLACK_CHANNEL: tests-e2e
          SLACK_COLOR	: ${{job.status}}
          SLACK_ICON: https://www.clipartmax.com/png/middle/179-1795386_patient-success-success-icon-png.png
          SLACK MESSAGE: 'Testes realizados com sucesso :white_check_mark:'
          SLACK TITLE: 'Testes realizados com sucesso :white_check_mark:'
          SLACK USERNAME: SUCESSO


      - name: Slack Notification - Failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL}}
          SLACK_CHANNEL: tests-e2e
          SLACK_COLOR	: ${{job.status}}
          SLACK_ICON: https://png.pngtree.com/png-clipart/20220119/ourmid/pngtree-cartoon-hand-drawn-error-icon-png-image_4235046.png
          SLACK MESSAGE: 'Erro ao executar os testes! :fire:'
          SLACK TITLE: 'Erro ao executar os testes! :fire:'
          SLACK USERNAME: ERRO
     
     
