name: Build and run Maestro tests (Native Android)

on:
  push:
    branches: [ main ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Run Maestro Cloud
        id: maestro
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: android.wdio.native.app.v1.0.8.apk
          workspace: '.maestro/'

      - name: Parse maestro tests and send results to slack
        id: test-results
        uses: brett-james-rocketlab/maestro-test-results-to-slack@main
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Send Slack Notification
        if: always()
        run: |
          STATUS="${{ steps.maestro.outcome }}"
          if [ "$STATUS" == "success" ]; then
            MESSAGE="✅ Testes finalizados com sucesso no Maestro Cloud!"
          else
            MESSAGE="❌ Falha ao executar testes no Maestro Cloud!"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\": \"$MESSAGE\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
